version: '3.8'

x-function: &python
  volumes:
    - ./app:/app:rw
    - poetry-volume:/opt/poetry:delegated
  environment: &env-vars
    POETRY_HOME: /opt/poetry
  networks:
    - internal
  env_file:
    .env

services:

  app:
    <<: *python
    container_name: ${PROJECT_SLUG}_app
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file:
      - .env
    restart: always

  neo4j:
    image: neo4j:latest
    container_name: ${PROJECT_SLUG}_neo4j
    environment:
      NEO4J_AUTH: neo4j/${DB_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - internal

  nginx:
    build: nginx/local
    container_name: ${PROJECT_SLUG}_nginx
    expose:
      - 80
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - internal

volumes:
  poetry-volume:
  neo4j_data:

networks:
  internal: